### ISSUE TITLE
Differences between `wxee` and `xee`

### ISSUE THREAD

**Issue by 12rambau** [aazuspan/wxee#73]
In Geo4Good this year, Google developers presented the xee lib. I was surprised to see it even though I was using wxee for a long time. are you aware of it ? https://github.com/google/Xee

If yes could you explain what is the main difference between your tool and theirs and if there are synergies ?

**Comment by aazuspan** [comment]
I haven't had a chance to dive too deeply into `Xee` yet, but at a glance, the core difference seems to be *when* in the process they download the data from Earth Engine.

`wxee` downloads images first and *then* packs them into an `xarray` dataset for further processing. Essentially it just provides convenience by automating the download and tracking image metadata in order to build a dataset with time coordinates.

My limited understanding of `Xee` (hopefully @alxmrs can correct me) is that it builds an `xarray` dataset based on just metadata, and only downloads data from Earth Engine once you choose to compute the dataset. That should theoretically be a more flexible solution by allowing you to take advantage of lazy evaluation and chunking to work with datasets that exceed the EE data limits (until you need to actually pull the data client-side).

I'm hoping to do a more in-depth comparison at some point and get a better idea of `Xee` capabilities. I'll follow up here when that happens.

**Comment by alxmrs** [comment]
That sounds like a fair comparison between the two libraries. For a more in depth explanation on the motivations of Xee, please read: https://github.com/google/Xee/blob/main/docs/why-xee.md
